//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.OData.Query.Commons {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SRResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.OData.Query.Commons.SRResources", typeof(SRResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last segment &apos;{0}&apos; is invalid. The last segment must be a navigation property or type segment in $expand..
        /// </summary>
        internal static string ExpandPath_InvalidLastSegment {
            get {
                return ResourceManager.GetString("ExpandPath_InvalidLastSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The segment &apos;{0}&apos; of segment type kind &apos;{1}&apos; is invalid. The last segment must be a navigation property or type segment in $expand..
        /// </summary>
        internal static string ExpandPath_LastSegmentMustBeNavigationPropertyOrTypeSegment {
            get {
                return ResourceManager.GetString("ExpandPath_LastSegmentMustBeNavigationPropertyOrTypeSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple navigation properties &apos;{0}&apos;, &apos;{1}&apos;... are found in $expand. The last segment, and only the last segment, can be a navigation property in $expand..
        /// </summary>
        internal static string ExpandPath_MultipleNavigationProperties {
            get {
                return ResourceManager.GetString("ExpandPath_MultipleNavigationProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error: character &apos;{0}&apos; is not valid at position {1} in &apos;{2}&apos;..
        /// </summary>
        internal static string ExpressionLexer_InvalidCharacter {
            get {
                return ResourceManager.GetString("ExpressionLexer_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ExpressionVisitor_UnsupportedExpression {
            get {
                return ResourceManager.GetString("ExpressionVisitor_UnsupportedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;)&apos; or &apos;,&apos; expected at position {0} in &apos;{1}&apos;..
        /// </summary>
        internal static string QueryOptionParser_CloseParenOrCommaExpected {
            get {
                return ResourceManager.GetString("QueryOptionParser_CloseParenOrCommaExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;(&apos; expected at position {0} in &apos;{1}&apos;..
        /// </summary>
        internal static string QueryOptionParser_OpenParenExpected {
            get {
                return ResourceManager.GetString("QueryOptionParser_OpenParenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query option &apos;{0}&apos; was specified more than once, but it must be specified at most once when case-insensitive &apos;{1}&apos; and No-dollar sign prefix &apos;{2}&apos;..
        /// </summary>
        internal static string QueryOptionParser_QueryParameterMustBeSpecifiedOnce {
            get {
                return ResourceManager.GetString("QueryOptionParser_QueryParameterMustBeSpecifiedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token kind &apos;{0}&apos; expected, but kind &apos;{1}&apos; presented..
        /// </summary>
        internal static string QueryOptionParser_TokenKindExpected {
            get {
                return ResourceManager.GetString("QueryOptionParser_TokenKindExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to tokenize the expression &apos;{0}&apos; in &apos;{1}&apos; parser..
        /// </summary>
        internal static string QueryParser_FailedToTokenizeExpression {
            get {
                return ResourceManager.GetString("QueryParser_FailedToTokenizeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for $count query option found. The $count query option requires &apos;true&apos;/&apos;false&apos;..
        /// </summary>
        internal static string QueryParser_InvalidBooleanQueryOptionValue {
            get {
                return ResourceManager.GetString("QueryParser_InvalidBooleanQueryOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string like &apos;{0}&apos; is not a valid &apos;$count&apos; option. Valid values are &apos;true&apos; or &apos;false&apos;..
        /// </summary>
        internal static string QueryParser_InvalidDollarCount {
            get {
                return ResourceManager.GetString("QueryParser_InvalidDollarCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for &apos;{1}&apos; query option found. The &apos;{1}&apos; query option requires an integer value..
        /// </summary>
        internal static string QueryParser_InvalidIntegerQueryOptionValue {
            get {
                return ResourceManager.GetString("QueryParser_InvalidIntegerQueryOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for &apos;{1}&apos; query option found. The &apos;{1}&apos; query option requires an integer value..
        /// </summary>
        internal static string QueryParser_InvalidIntegerValue {
            get {
                return ResourceManager.GetString("QueryParser_InvalidIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for &apos;{1}&apos; query option found. The &apos;{1}&apos; query option requires a non-negative integer value..
        /// </summary>
        internal static string QueryParser_InvalidNonNegativeIntegerValue {
            get {
                return ResourceManager.GetString("QueryParser_InvalidNonNegativeIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;$orderby&apos; expression &apos;{0}&apos; must evaluate to a single value of primitive type..
        /// </summary>
        internal static string QueryParser_OrderByExpressionNotSingleValue {
            get {
                return ResourceManager.GetString("QueryParser_OrderByExpressionNotSingleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unsupported query token kind &apos;{0}&apos; was found..
        /// </summary>
        internal static string QueryParser_UnsupportedQueryTokenKind {
            get {
                return ResourceManager.GetString("QueryParser_UnsupportedQueryTokenKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create lexer for the&apos;{0}&apos; expression..
        /// </summary>
        internal static string QueryTokenizer_FailToCreateLexer {
            get {
                return ResourceManager.GetString("QueryTokenizer_FailToCreateLexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key word &apos;{0}&apos; expected at position &apos;{1}&apos; in &apos;{2}&apos;..
        /// </summary>
        internal static string QueryTokenizer_KeyWordExpected {
            get {
                return ResourceManager.GetString("QueryTokenizer_KeyWordExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max depth must be greater than or equal to zero..
        /// </summary>
        internal static string QueryTokenizer_NegativeMaxDepth {
            get {
                return ResourceManager.GetString("QueryTokenizer_NegativeMaxDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range variable &apos;{0}&apos; has already been declared..
        /// </summary>
        internal static string QueryTokenizer_RangeVariableAlreadyDeclared {
            get {
                return ResourceManager.GetString("QueryTokenizer_RangeVariableAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursion depth doesn&apos;t match..
        /// </summary>
        internal static string QueryTokenizer_RecurseMismatch {
            get {
                return ResourceManager.GetString("QueryTokenizer_RecurseMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursion depth &apos;{0}&apos; is exceeded allowed limit &apos;{1}&apos;..
        /// </summary>
        internal static string QueryTokenizer_RecurseTooDeep {
            get {
                return ResourceManager.GetString("QueryTokenizer_RecurseTooDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token kind &apos;{0}&apos; expected, but kind &apos;{1}&apos; presented..
        /// </summary>
        internal static string QueryTokenizer_TokenKindExpected {
            get {
                return ResourceManager.GetString("QueryTokenizer_TokenKindExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeSegment &apos;{0}&apos; cannot be the only segment in a $select..
        /// </summary>
        internal static string SelectPath_CannotOnlyHaveTypeSegment {
            get {
                return ResourceManager.GetString("SelectPath_CannotOnlyHaveTypeSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a segment &apos;{0}&apos; of type &apos;{1} in a select path, but only TypeSegment, NavigationPropertySegment, PropertySegment, OperationSegment or OpenPropertySegments are allowed..
        /// </summary>
        internal static string SelectPath_InvalidSelectPathSegmentType {
            get {
                return ResourceManager.GetString("SelectPath_InvalidSelectPathSegmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A navigation property &apos;{0}&apos; is in the middle of path. The navigation property can only be the last segment in $select..
        /// </summary>
        internal static string SelectPath_NavPropSegmentCanOnlyBeLastSegment {
            get {
                return ResourceManager.GetString("SelectPath_NavPropSegmentCanOnlyBeLastSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A digit was expected at position {0} in &apos;{1}&apos;..
        /// </summary>
        internal static string Tokenization_DigitExpected {
            get {
                return ResourceManager.GetString("Tokenization_DigitExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error: character &apos;{0}&apos; is not valid at position {1} in &apos;{2}&apos;..
        /// </summary>
        internal static string Tokenization_InvalidCharacter {
            get {
                return ResourceManager.GetString("Tokenization_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric string &apos;{0}&apos; is not a valid Int32/Int64/Double/Decimal..
        /// </summary>
        internal static string Tokenization_InvalidNumericString {
            get {
                return ResourceManager.GetString("Tokenization_InvalidNumericString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error at position {0} in &apos;{1}&apos;..
        /// </summary>
        internal static string Tokenization_SyntaxError {
            get {
                return ResourceManager.GetString("Tokenization_SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unterminated string literal at position {0} in &apos;{1}&apos;..
        /// </summary>
        internal static string Tokenization_UnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("Tokenization_UnterminatedStringLiteral", resourceCulture);
            }
        }
    }
}
