//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.OData.Query {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.OData.Query.OResource", typeof(OResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A digit was expected at position {0} in &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionLexer_DigitExpected {
            get {
                return ResourceManager.GetString("ExpressionLexer_DigitExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric string &apos;{0}&apos; is not a valid Int32/Int64/Double/Decimal..
        /// </summary>
        internal static string ExpressionLexer_InvalidNumericString {
            get {
                return ResourceManager.GetString("ExpressionLexer_InvalidNumericString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an unbalanced range expression, missing &apos;{0}&apos;..
        /// </summary>
        internal static string ExpressionLexer_UnbalancedRangeExpression {
            get {
                return ResourceManager.GetString("ExpressionLexer_UnbalancedRangeExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for $index query option found. The $index query option requires an integer value..
        /// </summary>
        internal static string QueryTokenizator_InvalidIndexQueryOptionValue {
            get {
                return ResourceManager.GetString("QueryTokenizator_InvalidIndexQueryOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for $skip query option found. The $skip query option requires a non-negative integer value..
        /// </summary>
        internal static string QueryTokenizator_InvalidSkipQueryOptionValue {
            get {
                return ResourceManager.GetString("QueryTokenizator_InvalidSkipQueryOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for $top query option found. The $top query option requires a non-negative integer value..
        /// </summary>
        internal static string QueryTokenizator_InvalidTopQueryOptionValue {
            get {
                return ResourceManager.GetString("QueryTokenizator_InvalidTopQueryOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query option &apos;{0}&apos; was specified more than once, but it must be specified at most once..
        /// </summary>
        internal static string QueryTokenizator_QueryOptionMustBeSpecifiedOnce {
            get {
                return ResourceManager.GetString("QueryTokenizator_QueryOptionMustBeSpecifiedOnce", resourceCulture);
            }
        }
    }
}
